Explicitly export functions
KAUTH/auto-click-auto pull request #14
Opened 2024-06-23 21:22 UTC by guy-av

Hey!

Got a small enhancement here, to comply with type checking tools requiring explicit exports of symbols.

## Background

I've come across a project that uses this package and trying to type-check using `mypy`, which fails as follows:

```
$ mypy --explicit-package-bases --ignore-missing-imports --strict .

error: Module "auto_click_auto" does not explicitly export attribute "enable_click_shell_completion"  [attr-defined]
```

2024-06-24 21:42 UTC, guy-av commented
@KAUTH would appreciate you taking a look :)

2024-06-25 10:18 UTC, KAUTH commented
Hey @guy-av thanks for investigating this and coming up with a proposal!

> I've come across a project that uses this package and trying to type-check using `mypy`, which fails as follows:

```
$ mypy --explicit-package-bases --ignore-missing-imports --strict .

error: Module "auto_click_auto" does not explicitly export attribute "enable_click_shell_completion"  [attr-defined]
```

To sum up, in the `mypy` type checking that was run, the `--strict` flag that's being used returns the error mentioned in the description, because of the `--no-implicit-reexport` strictness flag that is included with `--strict`.

I believe that instead of keeping track of an `all` or `__all__` list we can import using from-as. `click` itself follows a similar [paradigm](https://github.com/pallets/click/blob/main/src/click/__init__.py#L21). So, for example, in our case it would be:
```python
# This will re-export it as enable_click_shell_completion and allow other modules to import it
from .core import enable_click_shell_completion as enable_click_shell_completion
```
For more information, you can read https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport.

Note:
For packages that will be using older versions of `auto-click-auto` we can ignore this error explicitly when using stricter `mypy` flags, for example, with `# type: ignore[attr-defined]`.

2024-06-25 20:45 UTC, guy-av commented
> I believe that instead of keeping track of an `all` or `__all__` list we can import using from-as. `click` itself follows a similar [paradigm](https://github.com/pallets/click/blob/main/src/click/__init__.py#L21). So, for example, in our case it would be:
> 
> ```python
> 
> # This will re-export it as enable_click_shell_completion and allow other modules to import it
> 
> from .core import enable_click_shell_completion as enable_click_shell_completion
> 
> ```

Cool! Never knew from-as addresses this issue, I'll change the code to follow this notation

> For packages that will be using older versions of `auto-click-auto` we can ignore this error explicitly when using stricter `mypy` flags, for example, with `# type: ignore[attr-defined]`.

Definitely

Also possible with `mypy --implicit-reexport`.

2024-06-26 12:20 UTC, KAUTH requested changes
Looking good! Just a small style change required for CI to pass.

2024-06-26 12:20 UTC, KAUTH commented on auto_click_auto/__init__.py
> +from .core import enable_click_shell_completion_option as enable_click_shell_completion_option
The `isort` hook is failing on [CI](https://github.com/KAUTH/auto-click-auto/actions/runs/9669738028/job/26704739804?pr=14#step:5:72)
```suggestion
from .core import (
    enable_click_shell_completion as enable_click_shell_completion,
)
from .core import (
    enable_click_shell_completion_option as enable_click_shell_completion_option,
)
```

2024-06-26 18:50 UTC, KAUTH approved these changes
LGTM!
I will create a new patch version shortly, thanks again for contributing 🚀

2024-06-26 18:51 UTC, merged